name: Build and Push MongoDB Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ secrets.REPOSITORY_OWNER }}/mongo-seed

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update mongodb-version.txt in app-config
        run: |
          git clone https://x-access-token:${{ secrets.APP_CONFIG_TOKEN }}@github.com/${{ secrets.REPOSITORY_OWNER }}/app-config.git
          cd app-config
          echo "${{ github.sha }}" > mongodb-version.txt
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add mongodb-version.txt
          git commit -m "Update MongoDB image tag to ${{ github.sha }}"
          git push
